import 'package:flutter/material.dart';

class Product {
  final int id;
  final String title, description, name, lastname, profesion;
  final List<String> images;
  final List<Color> colors;
  final double rating, price;
  final bool isFavourite, isPopular, isHome;

  Product({
    required this.id,
    required this.images,
    required this.colors,
    required this.name,
    required this.lastname,
    required this.profesion,
    this.rating = 0.0,
    this.isFavourite = false,
    this.isPopular = false,
    this.isHome = false,
    required this.title,
    required this.price,
    required this.description,
  });
}

// Our demo Products

List<Product> demoProducts = [
  Product(
      id: 1,
      images: [
        'assets/images.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Domiciliary",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Alex",
      lastname: "Tumy",
      profesion: "Domiciliary",
      description: "Hi i am Alex i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/chica1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Domiciliary",
      price: 20.000,
      description: "Hi i am Aleja i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Aleja",
      lastname: "Gom",
      profesion: "Domiciliary"),
  Product(
      id: 3,
      images: [
        'assets/chica2.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Domiciliary",
      price: 10.000,
      description: "Hi i am Ana i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Ana",
      lastname: "Piza",
      profesion: "Domiciliary"),
  Product(
      id: 4,
      images: [
        'assets/chico1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Domiciliary",
      price: 20.20,
      description: "Hi i am Juan i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Juan",
      lastname: "Gito",
      profesion: "Domiciliary"),
];

List<Product> demoProducts2 = [
  Product(
      id: 1,
      images: ['assets/chica3.jpg', 'assets/domi.jpg'],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Domiciliary",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Alexa",
      lastname: "Cosi",
      profesion: "Baby sitter",
      description: "Hi i am Alexa i would like to serve you in any need "),
  Product(
      id: 2,
      images: ['assets/chica4.jpg', 'assets/mari.jpg'],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Maid",
      price: 20.000,
      description: "Hi i am Aleja i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Aleja",
      lastname: "Tux",
      profesion: "Maid"),
  Product(
      id: 3,
      images: ['assets/chico2.jpg', 'assets/chef.jpg'],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Chef",
      price: 10.000,
      description: "Hi i am Jon i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Jon",
      lastname: "Snow",
      profesion: "Chef"),
  Product(
      id: 4,
      images: [
        'assets/chico6.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Carpenter",
      price: 20.20,
      description: "Hi i am Chad i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Chad",
      lastname: "Plon",
      profesion: "Carpenter"),
  Product(
      id: 5,
      images: [
        'assets/chico4.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Vet",
      price: 20.20,
      description: "Hi i am Vlad i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Vlad",
      lastname: "Fox",
      profesion: "Dog walker"),
];

List<Product> demoProducts3 = [
  Product(
      id: 1,
      images: [
        'assets/chico7.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Doctor",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Richie",
      lastname: "Cod",
      profesion: "Doctor",
      description: "Hi i am Richie i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/chica5.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Nurse",
      price: 20.000,
      description: "Hi i am Jen i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Jen",
      lastname: "Dock",
      profesion: "Nurse"),
  Product(
      id: 3,
      images: [
        'assets/chica6.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Psychologist",
      price: 10.000,
      description: "Hi i am Loki i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Loki",
      lastname: "Chia",
      profesion: "Psychologist"),
  Product(
      id: 4,
      images: [
        'assets/chica1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Lawyer",
      price: 20.20,
      description: "Hi i am Tere i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Tere",
      lastname: "Fran",
      profesion: "Lawyer"),
];

List<Product> demoProducts4 = [
  Product(
      id: 1,
      images: [
        'assets/chico6.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Graphic Designer",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Finn",
      lastname: "Hen",
      profesion: "Designer",
      description: "Hi i am Finn i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/chica1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Painter",
      price: 20.000,
      description: "Hi i am Ann i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Ann",
      lastname: "Paez",
      profesion: "Painter"),
  Product(
      id: 3,
      images: [
        'assets/chico7.jpg',
        'assets/ejem1.jpg',
        'assets/ejem2.jpg',
        'assets/ejem3.jpg',
        'assets/ejem4.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Photographer",
      price: 10.000,
      description:
          "Hi i am Leo i would like to serve you in any need, i took an artistic course on camelly and now i take the best photos in the world! Book now! ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Leo",
      lastname: "Jix",
      profesion: "Photographer"),
  Product(
      id: 4,
      images: [
        'assets/chica2.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Dancer",
      price: 20.20,
      description: "Hi i am Brit i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Brit",
      lastname: "Gin",
      profesion: "Dancer"),
];

List<Product> demoProducts5 = [
  Product(
      id: 1,
      images: [
        'assets/chico4.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Guitar",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Chon",
      lastname: "Pin",
      profesion: "Guitar",
      description: "Hi i am Chon i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/chico6.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Percussionist",
      price: 20.000,
      description: "Hi i am E.T i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "E.T",
      lastname: "Jany",
      profesion: "Percussionist"),
  Product(
      id: 3,
      images: [
        'assets/chica3.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Singer",
      price: 10.000,
      description: "Hi i am Kate i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Kate",
      lastname: "Stel",
      profesion: "Singer"),
  Product(
      id: 4,
      images: [
        'assets/chica4.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Saxophonist",
      price: 20.20,
      description: "Hi i am Sofi i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Sofi",
      lastname: "Jin",
      profesion: "Saxophonist"),
];

List<Product> demoProducts6 = [
  Product(
      id: 1,
      images: [
        'assets/chica5.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Math teacher",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Mel",
      lastname: "Cass",
      profesion: "Math teacher",
      description: "Hi i am Mel i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/images.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Spanish teacher",
      price: 20.000,
      description: "Hi i am Jim i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Jim",
      lastname: "Gani",
      profesion: "Spanish teacher"),
  Product(
      id: 3,
      images: [
        'assets/chica6.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Makeup teacher",
      price: 10.000,
      description: "Hi i am Ana i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Ana",
      lastname: "Piza",
      profesion: "Makeup teacher"),
  Product(
      id: 4,
      images: [
        'assets/chico7.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Soccer trainer",
      price: 20.20,
      description: "Hi i am Juan i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Juan",
      lastname: "Gito",
      profesion: "Soccer trainer"),
];

List<Product> demoProducts7 = [
  Product(
      id: 1,
      images: [
        'assets/chico2.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Taxi driver",
      price: 15.000,
      rating: 4.8,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Alex",
      lastname: "Cass",
      profesion: "Taxi driver",
      description: "Hi i am Alex i would like to serve you in any need "),
  Product(
      id: 2,
      images: [
        'assets/chica1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Driver",
      price: 20.000,
      description: "Hi i am Aleja i would like to serve you in any need ",
      rating: 4.1,
      isPopular: true,
      isHome: true,
      name: "Aleja",
      lastname: "Uri",
      profesion: "Driver"),
  Product(
      id: 3,
      images: [
        'assets/chico4.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "Bodyguard",
      price: 10.000,
      description: "Hi i am Jim i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isPopular: true,
      isHome: true,
      name: "Jim",
      lastname: "Pino",
      profesion: "Bodyguard"),
  Product(
      id: 4,
      images: [
        'assets/chico1.jpg',
      ],
      colors: [
        Color(0xFFF6625E),
        Color(0xFF836DB8),
        Color(0xFFDECB9C),
        Colors.white,
      ],
      title: "shooting guard",
      price: 20.20,
      description: "Hi i am Juan i would like to serve you in any need ",
      rating: 4.1,
      isFavourite: true,
      isHome: true,
      name: "Juan",
      lastname: "Gito",
      profesion: "shooting guard"),
];
